swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions API
      description: API for getting a list of transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: A list of user's transactions
          schema:
            type: array
            items: 
              $ref: '#/definitions/TransactionApiResponse'
        '500':
          description: Internal Server Error
  /transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions API
      description: API for getting the detail of a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: Id of a transaction
          required: true
          type: number
      produces:
        - application/json
      responses:
        '200':
          description: The detail of a transaction
          schema:
            $ref: '#/definitions/TransactionDetailApiResponse'
        '500':
          description: Internal Server Error
          
  /transactions/{id}/notes:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions API
      description: API for setting transaction's notes
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: Id of a transaction
          required: true
          type: number
        - in: body
          name: body
          description: Update the notes attribute
          required: true
          schema:
            $ref: '#/definitions/TransactionNotes'
      produces:
        - application/json
      responses:
        '200':
          description: The detail of the updated transaction
          schema:
            $ref: '#/definitions/TransactionDetailApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  
  /transactions/{id}/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions API
      description: API for setting transaction's category
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: Id of a transaction
          required: true
          type: number
        - in: body
          name: body
          description: Update the category attribute
          required: true
          schema:
            $ref: '#/definitions/TransactionCategory'
      produces:
        - application/json
      responses:
        '200':
          description: The detail of the updated transaction
          schema:
            $ref: '#/definitions/TransactionDetailApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  TransactionNotes:
    type: object
    properties:
      notes: 
        type: string
  TransactionCategory:
    type: object
    properties:
      category: 
        type: string
  TransactionApiResponse:
    type: object
    properties:
      id:
        type: number
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
  TransactionDetailApiResponse:
    type: object
    properties:
      type:
        type: string
      notes:
        type: string
      category:
        type: string
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

